# Generated by Django 5.0.7 on 2024-10-26 02:27

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('images', '0003_image_created_at_alter_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('nickname', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_protected', models.BooleanField(default=False)),
                ('is_registered', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(null=True)),
                ('bio', models.CharField(default='', max_length=511)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('header_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_users', to='images.image')),
                ('profile_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_users', to='images.image')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('default_manager', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ThirdPartyIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('kakao', 'Kakao')], max_length=64)),
                ('provider_id', models.PositiveBigIntegerField()),
                ('provider_email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_party_integrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
