# Generated by Django 5.0.7 on 2024-09-27 05:31

import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to=images.models.image_upload_to('original'))),
                ('small', models.ImageField(null=True, upload_to=images.models.image_upload_to('small'))),
                ('medium', models.ImageField(null=True, upload_to=images.models.image_upload_to('medium'))),
            ],
        ),
    ]
