# Generated by Django 5.0.7 on 2024-09-27 05:50

import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='large',
            field=models.ImageField(null=True, upload_to=images.models.image_upload_to('large')),
        ),
    ]
