# Generated by Django 5.0.7 on 2024-09-28 02:11

import django.utils.timezone
import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_large'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(null=True, upload_to=images.models.image_upload_to('original')),
        ),
    ]
